services:
  postgres-primary:
    image: postgres:16-alpine
    container_name: postgres-primary
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ratelimiter
      - POSTGRES_USER=ratelimiter
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ./primary-init:/docker-entrypoint-initdb.d
    command: >
      postgres  -c wal_level=replica
                -c max_wal_senders=10
                -c max_replication_slots=10
                -c hot_standby=on
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ratelimiter -d ratelimiter"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-replica:
    image: postgres:16-alpine
    container_name: postgres-replica
    ports:
      - "5433:5432"
    depends_on:
      postgres-primary:
        condition: service_healthy
    environment:
      - PGPASSWORD=replicator_pass
    command: >
      bash -c "
      until pg_basebackup -h postgres-primary -D /var/lib/postgresql/data -U replicator -vP -R;
      do echo 'Waiting for primary...'; sleep 2; done &&
      exec docker-entrypoint.sh postgres
      "
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: redis-limiter
    ports:
      - "6379:6379"
    #environment:
    #  - REDIS_ARGS=--save 60 1
  app:
    build: .
    container_name: rate-limiter-spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      postgres-primary:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ratelimiter
      - SPRING_DATASOURCE_USERNAME=ratelimiter
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
volumes:
    postgres_primary_data:
    postgres_replica_data: