spring.application.name=RateLimiter

#Redis Config
spring.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.redis.port=${SPRING_DATA_REDIS_PORT:6379}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.redis.enabled=true

#DB Config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/expense}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

#Secrets
jwt.token.secret-key=${JWT_SECRET_KEY}
aes.encryption.secret-key=${AES_SECRET_KEY}


#********************************LOGGERS******************************

#logging.level.com.sushant=DEBUG
#logging.level.root=DEBUG
#logging.level.org.springframework.context=DEBUG
#logging.level.org.springframework.beans.factory=DEBUG
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE